Minimum-required-API-version = "1.12.5" # 最低兼容的API版本，必需
Target-API-version = "1.12.6" # 目标的API版本，必需
name = "demo" # 项目名及模块 root 包名，必需
version = "1.0.0" # 模块版本信息，必需

[compile-option] # 额外编译命令选项，非必需(可以空着但不能删除)
version = true
fapi_version = "object"
